version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0:8000
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16.8
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5324:5324'

  redis:
    image: redis:7.4.3
    env_file:
      - .env
    ports:
      - '6379:6379'

  celery:
    build: .
    depends_on:
      - redis
    command: celery -A your_project worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
networks:
  default:

volumes:
  postgres_data:
  static_volume: